<div class="container-fluid">
    <h1><?php echo $this->escape($this->pageTitle) ?></h1>
    Дата/время обновления: <span id="refresh_time"></span>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <button type="button" id="btn_refresh" class="btn btn-default" onclick="refreshCurrencyCourse()"><span class="glyphicon glyphicon-refresh"></span> Обновить курс валют</button>
                    <button type="button" id="btn_select" class="btn btn-default" onclick="selectCurrencyCourse()">Выбрать перечень курсов валют</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row">&nbsp;</div>

    <div class="row">
        <div class="col-md-12">
            <table class="table table-condensed">
                <tr>
                    <th class="col-md-1">Цифр. код</th>
                    <th class="col-md-1">Букв. код</th>
                    <th class="col-md-1">Единиц</th>
                    <th class="col-md-1">Валюта</th>
                    <th class="col-md-1">Курс</th>
                </tr>
                <tbody id="rows">
                    <tr>
                        <td colspan="5">Загрузка ...</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">Число записей <span class="badge" id="rowcount"></span></div>
    </div>

    <div class="modal fade" id="currencyForm" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Выберите курсы валют!</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-condensed">
                                <tr>
                                    <th class="col-md-1">#</th>
                                    <th class="col-md-1">Цифр. код</th>
                                    <th class="col-md-1">Букв. код</th>
                                    <th class="col-md-1">Валюта</th>
                                </tr>
                            <tbody id="val_rows">
                                <tr>
                                    <td colspan="4">Загрузка ...</td>
                                </tr>
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-12">
                        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="saveCurrencyCourse()">Сохранить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal fade" id="msgBoxForm" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Внимание!</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <span id="msgBoxText"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-12">
                        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="saveCurrencyCourse()">Сохранить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


