<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
    </head>
    <body>     
<?php echo $this->layout()->content; ?>
    </body>
</html>