<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <link href="/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css"/>
        <link href="/bootstrap/css/theme.css" rel="stylesheet" type="text/css"/>
        <link href="/css/site.css" rel="stylesheet" type="text/css"/>
        <link href="/jquery-ui-1.11.4/jquery-ui.min.css" rel="stylesheet" type="text/css"/>
        <link href="/jquery-ui-1.11.4/jquery-ui.theme.min.css" rel="stylesheet" type="text/css"/>
        <script src="/js/jquery-1.12.0.min.js" type="text/javascript"></script>
        <script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/jquery-ui-1.11.4/jquery-ui.min.js" type="text/javascript"></script>
    </head>
    <body>     
<?php echo $this->layout()->content; ?>
    </body>
</html>

